/**
 * Created by corentin on 27/01/17.
 */
//export const FETCH_TVSHOW_SUCCESS = 'FETCH_TVSHOW_SUCCESS';
export const CREATE_TVSHOW_SUCCESS = 'CREATE_TVSHOW_SUCCESS';
export const DELETE_TVSHOW_SUCCESS = 'DELETE_TVSHOW_SUCCESS';

export const FETCH_TVSHOWS_SUCCESS = 'FETCH_TVSHOWS_SUCCESS';